apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: devops-test
  name: devops-test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devops-test
  strategy:
  template:
    metadata:
      labels:
        app: devops-test
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: devops-test
      initContainers:
        - name: wait-for-db
          image: busybox
          command: ["sh", "-c", "until nc -z -v -w1 mysql 3306; do echo 'Waiting for the database to be up...'; sleep 5; done"]
      tolerations:
        - key: "system"
          operator: "Exists"
          effect: "NoSchedule"
      containers:
      - image: devops-test
        imagePullPolicy: IfNotPresent
        name: devops-test
        env:
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                key: mysql-root-password
                name: mysql
          - name: NODE_NAME
            value: "minikube-test"
        ports:
          - containerPort: 8000
            name: http
            protocol: TCP
        resources:
          requests:
            cpu: 1
            memory: 1G
          limits:
            cpu: 2
            memory: 2G
